This is makeindex, version 2.15 [TeX Live 2019/dev] (kpathsea + Thai support).
Scanning style file ./network_slicing.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file network_slicing.acn....done (60 entries accepted, 0 rejected).
Sorting entries....done (357 comparisons).
Generating output file network_slicing.acr....done (138 lines written, 0 warnings).
Output written in network_slicing.acr.
Transcript written in network_slicing.alg.
